- name: Update Prometheus Configuration
  ansible.builtin.template:
    src: promotheus.yml
    dest: /opt/promotheus/promotheus.yml

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted